;;; ai-code-backends-infra.el --- Infrastructure for AI Code Terminals  -*- lexical-binding: t; -*-

;; Author: Yoav Orot, Kang Tu, Silex, Steve Molitor, AI Agent
;; SPDX-License-Identifier: Apache-2.0

;; Keywords: tools, convenience

;;; Commentary:
;; This library provides common infrastructure for AI-powered terminal interfaces,
;; including terminal backend abstraction (vterm/eat), window management,
;; and performance optimizations like anti-flicker and reflow glitch prevention.
;; Code was generated by AI Agent, using
;; https://github.com/manzaltu/claude-code-ide.el as reference
;; multi-session support came from claude-code.el.  Thanks Steve Molitor.

;;; Code:

(require 'cl-lib)
(require 'seq)
(require 'subr-x)
(require 'ai-code-editor-viewport)
(require 'ai-code-session)
(require 'ai-code-session-link)
;; Terminal-specific implementations live in dedicated modules so this
;; file can stay focused on shared session orchestration.
(require 'ai-code-backends-infra-vterm)
(require 'ai-code-backends-infra-eat)
(require 'ai-code-backends-infra-ghostel)

(declare-function ai-code--session-handle-at-input "ai-code-input" ())
(declare-function ai-code--session-project-root "ai-code-utils" ())
(declare-function ai-code-mcp-agent-refresh-source-context
                  "ai-code-mcp-agent" (agent-buffer source-buffer))

;;; Customization

(defgroup ai-code-backends-infra nil
  "Infrastructure for AI Code terminals."
  :group 'tools)

(defcustom ai-code-backends-infra-terminal-backend 'vterm
  "Terminal backend to use for sessions.
Can be either `vterm', `eat', or `ghostel'."
  :type '(choice (const :tag "vterm" vterm)
                 (const :tag "eat" eat)
                 (const :tag "ghostel" ghostel))
  :group 'ai-code-backends-infra)

(defcustom ai-code-backends-infra-window-side 'right
  "Side of the frame where the window should appear."
  :type '(choice (const :tag "Left" left)
                 (const :tag "Right" right)
                 (const :tag "Top" top)
                 (const :tag "Bottom" bottom))
  :group 'ai-code-backends-infra)

(defcustom ai-code-backends-infra-window-width 90
  "Body width of the side window when opened on left or right."
  :type 'integer
  :group 'ai-code-backends-infra)

(defcustom ai-code-backends-infra-window-height 20
  "Height of the side window when opened on top or bottom."
  :type 'integer
  :group 'ai-code-backends-infra)

(defcustom ai-code-backends-infra-use-side-window t
  "Whether to display the terminal in a side window."
  :type 'boolean
  :group 'ai-code-backends-infra)

(defcustom ai-code-backends-infra-focus-on-open t
  "Whether to focus the terminal window when it opens."
  :type 'boolean
  :group 'ai-code-backends-infra)

(defcustom ai-code-backends-infra-terminal-initialization-delay 0.1
  "Initialization delay for terminal stability."
  :type 'number
  :group 'ai-code-backends-infra)

(defcustom ai-code-backends-infra-prevent-reflow-glitch t
  "Workaround for terminal scrolling bug #1422."
  :type 'boolean
  :group 'ai-code-backends-infra)

(defcustom ai-code-backends-infra-strip-alternate-screen t
  "Strip alternate screen buffer sequences from terminal output.
When non-nil, remove the escape sequences that switch to and from
the alternate screen buffer (\\e[?1049h and \\e[?1049l).  TUI
applications like GitHub Copilot CLI hardcode these sequences,
which disables terminal scrollback.  Stripping them forces output
onto the normal screen buffer where scrollback is preserved."
  :type 'boolean
  :group 'ai-code-backends-infra)

(defcustom ai-code-backends-infra-scrollback-inject-interval 1.0
  "Minimum seconds between scrollback-preservation injections.
When a TUI application redraws via synchronized output, we inject
newlines to push visible content into the scrollback ring.  This
interval prevents flooding the scrollback with duplicate frames."
  :type 'number
  :group 'ai-code-backends-infra)

(defcustom ai-code-backends-infra-use-paste-backends '("antigravity")
  "List of backend session prefixes for which multiline inputs should be pasted.
This helps speed up sending multiline prompts to backends (like Antigravity)
that process character-by-character input slowly."
  :type '(repeat string)
  :group 'ai-code-backends-infra)

;;; Variables

(defvar ai-code-backends-infra--processes (make-hash-table :test 'equal)
  "Hash table mapping session keys to their processes.")

(defvar ai-code-backends-infra--last-accessed-buffer nil
  "The most recently accessed AI Code buffer.")

(defvar ai-code-backends-infra--directory-buffer-map (make-hash-table :test 'equal)
  "Hash table mapping (prefix . directory) to last selected session buffer.")

(defvar ai-code-backends-infra--file-session-map (make-hash-table :test 'equal)
  "Hash table mapping (prefix workspace file) to attached session buffers.")

(defvar ai-code-backends-infra--preferred-session-buffer nil
  "Preferred session buffer to place first when prompting for session selection.")

(defvar ai-code-backends-infra--launch-program nil
  "AI CLI program associated with the terminal session currently being created.
This is dynamically bound by `ai-code-backends-infra--start-cli-session' so
terminal-specific startup code can identify the CLI without duplicating the
backend registry.")

(defvar ai-code-backends-infra--reflow-advised-handlers nil
  "Resize handlers currently advised with reflow filter.")

(defvar-local ai-code-backends-infra--idle-timer nil
  "Timer for detecting idle state (response completion).")

(defvar-local ai-code-backends-infra--response-seen nil
  "Non-nil when the current response has been observed.
Observation happens either by the buffer being visible or by a notification
being sent for the response completion.")

(defvar-local ai-code-backends-infra--last-meaningful-output-time nil
  "Float timestamp of the most recent meaningful output.")

(defvar-local ai-code-backends-infra--session-directory nil
  "Normalized working directory associated with the current session buffer.")

(defvar-local ai-code-backends-infra--session-terminal-backend nil
  "Terminal backend used by the current session buffer.")

(defvar-local ai-code-backends-infra--session-prefix nil
  "Backend prefix associated with the current session buffer.")

(defvar-local ai-code-backends-infra--session-task-file nil
  "Task file associated with the current session buffer, when available.")

(defvar-local ai-code-backends-infra--multiline-input-sequence nil
  "Terminal sequence sent for multiline input in the current session buffer.")

(defvar-local ai-code-backends-infra--terminal-active-cursor-type nil
  "Cursor type to restore when returning to terminal interaction mode.")

(defvar-local ai-code-backends-infra--navigation-cursor-active nil
  "Non-nil when Emacs temporarily owns the cursor for output navigation.")

(defvar ai-code-cli-args-history nil
  "History list for CLI args prompts.")

(defconst ai-code-backends-infra--uuid-regexp
  "[[:xdigit:]]\\{8\\}-[[:xdigit:]]\\{4\\}-[[:xdigit:]]\\{4\\}-[[:xdigit:]]\\{4\\}-[[:xdigit:]]\\{12\\}"
  "Regexp matching the general UUID 8-4-4-4-12 text structure.
This validates the textual shape, but not UUID version or variant bits.")

(defun ai-code-backends-infra--selected-session-id ()
  "Return active region text if it has a UUID session id."
  (when (use-region-p)
    (let ((candidate
           (string-trim
            (buffer-substring-no-properties (region-beginning) (region-end)))))
      (when (string-match-p
             (concat "\\`" ai-code-backends-infra--uuid-regexp "\\'")
             candidate)
        candidate))))

(defcustom ai-code-backends-infra-idle-delay 5.0
  "Delay in seconds of inactivity before considering response complete.
After this period of terminal inactivity, a notification may be sent
if the AI session buffer is not currently visible."
  :type 'number
  :group 'ai-code-backends-infra)

;;; Terminal Output Preservation

(defconst ai-code-backends-infra--alternate-screen-regexp
  "\033\\[\\?1049[hl]"
  "Regexp matching alternate screen buffer enter/exit sequences.
Matches \\e[?1049h (enter) and \\e[?1049l (exit).")

(defconst ai-code-backends-infra--screen-clear-regexp
  "\033\\[2J"
  "Regexp matching the Erase Display (ED 2) screen clear sequence.")

(defconst ai-code-backends-infra--scrollback-clear-regexp
  "\033\\[3J"
  "Regexp matching the Erase Display (ED 3) scrollback clear sequence.")

(defconst ai-code-backends-infra--sync-redraw-regexp
  "\033\\[\\?2026h\033\\[1;1H"
  "Regexp matching synchronized-update frame start with cursor home.
Copilot CLI uses \\e[?2026h (begin synchronized update) followed
immediately by \\e[1;1H (cursor to row 1, col 1) to redraw the
entire screen in place.")

(defvar ai-code-backends-infra-strip-alternate-screen-debug nil
  "When non-nil, log alternate-screen filter matches to *Messages*.
Set to t to debug scrollback-preservation transformations.")

(defvar-local ai-code-backends-infra--last-scrollback-inject-time 0
  "Timestamp of the last scrollback-preservation injection.
Used to throttle injections per
`ai-code-backends-infra-scrollback-inject-interval'.")

(defvar-local ai-code-backends-infra--sync-redraw-scrollback nil
  "Non-nil means inject scrollback-preserving newlines before redraws.
This applies to synchronized-update frame redraws (\\e[?2026h\\e[1;1H).
Backends that hardcode alternate screen buffer should set this
to t via their post-start-fn.")

(defun ai-code-backends-infra--scroll-to-scrollback-sequence ()
  "Return a sequence that pushes visible content into scrollback.
Move cursor to the last row, emit enough newlines to scroll all
visible lines into the scrollback buffer, then cursor home."
  (let ((height (or (when-let* ((win (get-buffer-window (current-buffer) t)))
                      (window-body-height win))
                    50)))
    (concat "\033[" (number-to-string height) ";1H"
            (make-string height ?\n)
            "\033[H")))

(defun ai-code-backends-infra--log-alternate-screen-debug (str)
  "Log alternate-screen debug details for STR when debugging is enabled."
  (when (and ai-code-backends-infra-strip-alternate-screen-debug
             (string-match-p "\033\\[" str))
    (let ((visible (replace-regexp-in-string
                    "\033" "<ESC>" (substring str 0 (min 200 (length str))))))
      (message "alt-screen-filter: len=%d alt=%s 2J=%s 3J=%s H+J=%s sync=%s seq=[%s]"
               (length str)
               (if (string-match-p ai-code-backends-infra--alternate-screen-regexp str) "Y" "N")
               (if (string-match-p ai-code-backends-infra--screen-clear-regexp str) "Y" "N")
               (if (string-match-p ai-code-backends-infra--scrollback-clear-regexp str) "Y" "N")
               (if (string-match-p "\033\\[H.*\033\\[J\\|\033\\[H.*\033\\[0J" str) "Y" "N")
               (if (string-match-p ai-code-backends-infra--sync-redraw-regexp str) "Y" "N")
               visible))))

(defun ai-code-backends-infra--strip-alternate-screen-transitions (str)
  "Strip alternate screen transitions from STR."
  (replace-regexp-in-string ai-code-backends-infra--alternate-screen-regexp "" str))

(defun ai-code-backends-infra--maybe-inject-screen-clear-scrollback (str scroll-seq now inject-ok)
  "Inject SCROLL-SEQ for screen-clear sequences in STR when allowed.
NOW is the current timestamp and INJECT-OK controls throttle gating."
  (if (and inject-ok
           (string-match-p ai-code-backends-infra--screen-clear-regexp str))
      (progn
        (setq ai-code-backends-infra--last-scrollback-inject-time now)
        (replace-regexp-in-string
         ai-code-backends-infra--screen-clear-regexp
         scroll-seq str t t))
    str))

(defun ai-code-backends-infra--strip-scrollback-clear (str)
  "Strip scrollback-clear sequences from STR."
  (replace-regexp-in-string ai-code-backends-infra--scrollback-clear-regexp "" str))

(defun ai-code-backends-infra--maybe-inject-home-erase-scrollback (str scroll-seq now inject-ok)
  "Inject SCROLL-SEQ for home+erase redraws in STR when allowed.
NOW is the current timestamp and INJECT-OK controls throttle gating."
  (let ((home-erase-re "\033\\[H\033\\[J\\|\033\\[H\033\\[0J"))
    (if (and inject-ok
             (string-match-p home-erase-re str))
        (progn
          (setq ai-code-backends-infra--last-scrollback-inject-time now)
          (replace-regexp-in-string
           home-erase-re
           (concat scroll-seq "\033[H") str t t))
      str)))

(defun ai-code-backends-infra--maybe-inject-sync-redraw-scrollback (str scroll-seq)
  "Inject SCROLL-SEQ before synchronized redraw frames in STR when allowed."
  (if (and ai-code-backends-infra--sync-redraw-scrollback
           (> (length str) 500)
           (string-match ai-code-backends-infra--sync-redraw-regexp str)
           (>= (- (float-time)
                  ai-code-backends-infra--last-scrollback-inject-time)
               ai-code-backends-infra-scrollback-inject-interval))
      (progn
        (setq ai-code-backends-infra--last-scrollback-inject-time (float-time))
        (let ((match-start (match-beginning 0)))
          (concat (substring str 0 match-start)
                  scroll-seq
                  (substring str match-start))))
    str))

(defun ai-code-backends-infra--strip-alternate-screen-sequences (str)
  "Normalize terminal sequences in STR to preserve scrollback.
When `ai-code-backends-infra-strip-alternate-screen' is non-nil and
the current buffer is an AI session buffer, apply these transformations:
1. Strip alternate screen enter/exit (\\e[?1049h, \\e[?1049l).
2. Convert screen clear (\\e[2J) to a newline-scroll sequence so
   the current content is pushed into scrollback.  Throttled via
   `ai-code-backends-infra-scrollback-inject-interval'.
3. Strip scrollback clear (\\e[3J).
4. Convert erase-to-end (\\e[J / \\e[0J) preceded by cursor-home
   into a scrollback-preserving sequence.  Throttled to avoid
   flooding the scrollback ring with repeated TUI frames.
5. Detect synchronized-update frame redraws (\\e[?2026h\\e[1;1H)
   and inject scrollback preservation before the frame, throttled
   to avoid flooding."
  (if (and ai-code-backends-infra-strip-alternate-screen
           (ai-code-backends-infra--session-buffer-p (current-buffer)))
      (let* ((result str)
             (scroll-seq (ai-code-backends-infra--scroll-to-scrollback-sequence))
             (now (float-time))
             (inject-ok (>= (- now
                               ai-code-backends-infra--last-scrollback-inject-time)
                            ai-code-backends-infra-scrollback-inject-interval)))
        (ai-code-backends-infra--log-alternate-screen-debug str)
        ;; 1. Strip alternate screen transitions.
        (setq result (ai-code-backends-infra--strip-alternate-screen-transitions result))
        ;; 2. Convert ED 2 (clear screen) to newline-scroll, throttled
        ;;    to avoid flooding the scrollback ring with repeated TUI
        ;;    frames.  When throttled the plain \e[2J clears the screen
        ;;    without preserving content, which is acceptable since a
        ;;    recent snapshot was already pushed.
        (setq result
              (ai-code-backends-infra--maybe-inject-screen-clear-scrollback
               result scroll-seq now inject-ok))
        ;; 3. Strip ED 3 (clear scrollback).
        (setq result (ai-code-backends-infra--strip-scrollback-clear result))
        ;; 4. Convert cursor-home + erase-to-end (\e[H\e[J) into a
        ;;    scrollback-preserving sequence, throttled to avoid flooding
        ;;    the scrollback ring with repeated TUI frames (e.g. the
        ;;    Claude Code badge appearing on every redraw).
        (setq result
              (ai-code-backends-infra--maybe-inject-home-erase-scrollback
               result scroll-seq now inject-ok))
        ;; 5. Detect synchronized-update frames (\e[?2026h followed by
        ;;    cursor to row 1) and inject scrollback preservation before
        ;;    the frame redraw, throttled to avoid flooding the scrollback
        ;;    ring.  Only trigger on chunks > 500 bytes (meaningful
        ;;    redraws, not small cursor movements).  Guarded by the
        ;;    buffer-local `--sync-redraw-scrollback' flag so that only
        ;;    backends that explicitly opt in (e.g. Copilot CLI) get
        ;;    the injection.
        (setq result
              (ai-code-backends-infra--maybe-inject-sync-redraw-scrollback
               result scroll-seq))
        result)
    str))

(declare-function ai-code-notifications-response-ready "ai-code-notifications" (&optional backend-name))

(defun ai-code-backends-infra--output-meaningful-p (output)
  "Return non-nil if OUTPUT has meaningful printable content."
  (let* ((str (or output ""))
         ;; Strip OSC sequences (ESC ] ... BEL or ESC ] ... ESC \).
         (str (replace-regexp-in-string "\x1b\\][^\x07\x1b]*\\(?:\x07\\|\x1b\\\\\\)" "" str))
         ;; Strip ANSI escape sequences.
         (str (replace-regexp-in-string "\x1b\\[[0-9;?]*[ -/]*[@-~]" "" str))
         ;; Strip other control characters.
         (str (replace-regexp-in-string "[\x00-\x1f\x7f]" "" str)))
    (string-match-p "[^ \t\n\r]" str)))

(defun ai-code-backends-infra--buffer-user-visible-p (buffer)
  "Return non-nil when BUFFER is visible in any live window."
  (and (get-buffer-window-list buffer nil t) t))

(defun ai-code-backends-infra--check-response-complete (buffer)
  "Check if AI response is complete in BUFFER and notify if enabled."
  (when (buffer-live-p buffer)
    (with-current-buffer buffer
      (if (ai-code-backends-infra--idle-delay-elapsed-p)
          (let ((visible (ai-code-backends-infra--buffer-user-visible-p buffer)))
            (if visible
                (setq ai-code-backends-infra--response-seen t)
              (when (not ai-code-backends-infra--response-seen)
                (setq ai-code-backends-infra--response-seen t)
                (when (require 'ai-code-notifications nil t)
                  (when (fboundp 'ai-code-notifications-response-ready)
                    (let ((buffer-name (buffer-name buffer)))
                      ;; Extract backend name from buffer name format: *<backend>[<dir>]*
                      ;; Example: "*codex[my-project]*" extracts "codex"
                      ;; Regex breakdown:
                      ;;   \\*       - matches literal asterisk
                      ;;   \\(       - start capture group 1
                      ;;   [^[]+     - one or more chars that are not '['
                      ;;   \\)       - end capture group 1 (this is the backend name)
                      ;;   \\[       - matches literal '['
                      (when (string-match "\\*\\([^[]+\\)\\[" buffer-name)
                        (let ((backend-name (match-string 1 buffer-name)))
                          (ai-code-notifications-response-ready backend-name)))))))))
        (ai-code-backends-infra--schedule-idle-check)))))

(defun ai-code-backends-infra--schedule-idle-check ()
  "Schedule a check for response completion after idle period.
The timer is reset only after meaningful output is observed."
  (when ai-code-backends-infra--idle-timer
    (cancel-timer ai-code-backends-infra--idle-timer))
  (let ((buffer (current-buffer)))
    (setq ai-code-backends-infra--idle-timer
          (run-at-time ai-code-backends-infra-idle-delay nil
                       #'ai-code-backends-infra--check-response-complete
                       buffer))))

(defun ai-code-backends-infra--idle-delay-elapsed-p ()
  "Return non-nil when idle delay has elapsed since last output."
  (let ((last ai-code-backends-infra--last-meaningful-output-time))
    (or (null last)
        (>= (- (float-time) last) ai-code-backends-infra-idle-delay))))

(defun ai-code-backends-infra--note-meaningful-output ()
  "Record meaningful output and schedule idle tracking."
  (setq ai-code-backends-infra--response-seen nil
        ai-code-backends-infra--last-meaningful-output-time (float-time))
  (ai-code-backends-infra--schedule-idle-check))

(defun ai-code-backends-infra--configure-session-input-shortcuts ()
  "Install session-local shortcuts for prompt-oriented terminal input."
  (when (fboundp 'ai-code--session-handle-at-input)
    (local-set-key (kbd "@") #'ai-code--session-handle-at-input))
  (when (fboundp 'ai-code--session-handle-hash-input)
    (local-set-key (kbd "#") #'ai-code--session-handle-hash-input)))

;;; Terminal Backend Abstraction

(defun ai-code-backends-infra--terminal-ensure-backend ()
  "Ensure the selected terminal backend is available."
  (pcase ai-code-backends-infra-terminal-backend
    ('vterm (ai-code-backends-infra-vterm-ensure-backend))
    ('eat (ai-code-backends-infra-eat-ensure-backend))
    ('ghostel (ai-code-backends-infra-ghostel-ensure-backend))
    (_ (user-error "Invalid terminal backend: %s" ai-code-backends-infra-terminal-backend)))
  ;; Keep reflow advice synchronized with current backend/settings.
  (ai-code-backends-infra--sync-reflow-filter-advice))

(defun ai-code-backends-infra--terminal-dispatch (operation &rest args)
  "Dispatch OPERATION to the current terminal backend, passing ARGS.
Constructs function name as `ai-code-backends-infra-<backend>-<operation>'."
  (let* ((backend (ai-code-backends-infra--current-terminal-backend))
         (fn (intern (format "ai-code-backends-infra-%s-%s" backend operation))))
    (if (fboundp fn)
        (apply fn args)
      (error "Terminal backend %s does not support %s (looked up: %s)"
             backend operation fn))))

(defun ai-code-backends-infra--current-terminal-backend ()
  "Return terminal backend for current buffer operations."
  (or ai-code-backends-infra--session-terminal-backend
      ai-code-backends-infra-terminal-backend))

(defun ai-code-backends-infra--terminal-navigation-mode-p ()
  "Return non-nil when the current terminal buffer is in navigation mode."
  (pcase (ai-code-backends-infra--current-terminal-backend)
    ('vterm (ai-code-backends-infra-vterm-navigation-mode-p))
    ('eat (ai-code-backends-infra-eat-navigation-mode-p))
    ('ghostel (ai-code-backends-infra-ghostel-navigation-mode-p))
    (_ nil)))

(defun ai-code-backends-infra--sync-terminal-cursor ()
  "Hand cursor ownership between the terminal and Emacs navigation modes."
  (if (ai-code-backends-infra--terminal-navigation-mode-p)
      (unless ai-code-backends-infra--navigation-cursor-active
        (setq ai-code-backends-infra--terminal-active-cursor-type cursor-type
              ai-code-backends-infra--navigation-cursor-active t
              cursor-type t))
    (when ai-code-backends-infra--navigation-cursor-active
      (setq cursor-type ai-code-backends-infra--terminal-active-cursor-type
            ai-code-backends-infra--navigation-cursor-active nil))))

(defun ai-code-backends-infra--install-navigation-cursor-sync ()
  "Install buffer-local hooks for cursor handoff in terminal navigation modes."
  (ai-code-backends-infra--terminal-dispatch "install-navigation-cursor-sync"))

(defun ai-code-backends-infra--terminal-send-string (string &optional paste)
  "Send STRING to the terminal in the current buffer.
If PASTE is non-nil, send it as a pasted string."
  (if paste
      (ai-code-backends-infra--terminal-dispatch "send-string" string paste)
    (ai-code-backends-infra--terminal-dispatch "send-string" string)))

(defun ai-code-backends-infra--terminal-send-escape ()
  "Send escape key to the terminal in the current buffer."
  (ai-code-backends-infra--terminal-dispatch "send-escape"))

(defun ai-code-backends-infra--terminal-send-return ()
  "Send return key to the terminal in the current buffer."
  (ai-code-backends-infra--terminal-dispatch "send-return"))

(defun ai-code-backends-infra--terminal-send-backspace ()
  "Send backspace key to the terminal in the current buffer."
  (ai-code-backends-infra--terminal-dispatch "send-backspace"))

(defun ai-code-backends-infra--terminal-send-multiline-input ()
  "Send the configured multiline-input sequence for the current session buffer."
  (interactive)
  (unless ai-code-backends-infra--multiline-input-sequence
    (user-error "No multiline input sequence configured for this session"))
  (ai-code-backends-infra--terminal-send-string
   ai-code-backends-infra--multiline-input-sequence))

(defun ai-code-backends-infra--ensure-buffer-local-keymap ()
  "Use a buffer-local copy of the current local keymap."
  (use-local-map (copy-keymap (or (current-local-map)
                                  (make-sparse-keymap))))
  (current-local-map))

(defun ai-code-backends-infra--configure-multiline-input (sequence)
  "Configure multiline input keybindings in the current session buffer.
SEQUENCE is the terminal sequence sent for `S-<return>' and `C-<return>'."
  (if sequence
      (progn
        (setq-local ai-code-backends-infra--multiline-input-sequence sequence)
        (define-key (current-local-map) (kbd "S-<return>")
                    #'ai-code-backends-infra--terminal-send-multiline-input)
        (define-key (current-local-map) (kbd "C-<return>")
                    #'ai-code-backends-infra--terminal-send-multiline-input))
    (setq-local ai-code-backends-infra--multiline-input-sequence nil)
    (dolist (key (list (kbd "S-<return>") (kbd "C-<return>")))
      (when (eq (lookup-key (current-local-map) key)
                #'ai-code-backends-infra--terminal-send-multiline-input)
        (define-key (current-local-map) key nil)))))

(defun ai-code-backends-infra--configure-session-buffer (buffer
                                                         &optional escape-fn
                                                         multiline-input-sequence)
  "Configure BUFFER with shared session keybindings.
ESCAPE-FN is bound to `C-<escape>' when non-nil.
MULTILINE-INPUT-SEQUENCE configures `S-<return>' and `C-<return>' when non-nil."
  (with-current-buffer buffer
    (ai-code-backends-infra--ensure-buffer-local-keymap)
    (setq-local ai-code-editor-viewport--submit-function
                #'ai-code-backends-infra--terminal-send-return)
    (when escape-fn
      (define-key (current-local-map) (kbd "C-<escape>") escape-fn))
    (ai-code-backends-infra--configure-multiline-input
     multiline-input-sequence)
    (ai-code-session-link--linkify-session-region (point-min) (point-max))))

;;; Reflow and Window Management

(defun ai-code-backends-infra--terminal-resize-handler (&optional backend)
  "Retrieve the resize handling function for BACKEND.
When BACKEND is nil, use `ai-code-backends-infra-terminal-backend'."
  (pcase (or backend ai-code-backends-infra-terminal-backend)
    ('vterm (ai-code-backends-infra-vterm-resize-handler))
    ('eat (ai-code-backends-infra-eat-resize-handler))
    ('ghostel (ai-code-backends-infra-ghostel-resize-handler))
    (_ (error "Unsupported terminal backend"))))

(defun ai-code-backends-infra--session-buffer-p (buffer)
  "Check if BUFFER belongs to an AI session."
  (when-let* ((name (if (stringp buffer) buffer (buffer-name buffer))))
    (string-match-p "\\`\\*.*\\[.*\\].*\\*\\'" name)))

(defun ai-code-backends-infra--terminal-reflow-filter (original-fn &rest args)
  "Filter terminal reflows to prevent height-only resize triggers.
ORIGINAL-FN is the terminal resize function and ARGS are its arguments.
Suppress reflow when terminal width is unchanged or when the session
buffer is in scroll/copy mode, working around bug #1422."
  (let* ((base-result (apply original-fn args))
         (dimensions-stable t))
    (dolist (win (window-list))
      (when-let* ((buf (window-buffer win))
                  ((ai-code-backends-infra--session-buffer-p buf)))
        (let* ((new-width (window-width win))
               (cached-width (window-parameter win 'ai-code-backends-infra-cached-width)))
          (unless (eql new-width cached-width)
            (setq dimensions-stable nil)
            (set-window-parameter win 'ai-code-backends-infra-cached-width new-width)))))
    (cond
     ;; Not in a session buffer - pass through
     ((not (ai-code-backends-infra--session-buffer-p (current-buffer)))
      base-result)
     ;; In scroll/copy mode - suppress reflow to avoid disrupting navigation
     ((ai-code-backends-infra--terminal-navigation-mode-p)
      nil)
     ;; Width changed - allow reflow
     ((not dimensions-stable)
      base-result)
     ;; Height-only change with reflow glitch prevention - suppress
     (ai-code-backends-infra-prevent-reflow-glitch
      nil)
     ;; Default - pass through
     (t base-result))))

(defun ai-code-backends-infra--sync-reflow-filter-advice ()
  "Add or remove terminal reflow advice according to current settings."
  (let* ((resize-handler (ai-code-backends-infra--terminal-resize-handler))
         (enabled (and ai-code-backends-infra-prevent-reflow-glitch
                       (eq ai-code-backends-infra-terminal-backend 'eat))))
    (dolist (handler (cl-copy-list ai-code-backends-infra--reflow-advised-handlers))
      (unless (and enabled (eq handler resize-handler))
        (when (advice-member-p #'ai-code-backends-infra--terminal-reflow-filter
                               handler)
          (advice-remove handler
                         #'ai-code-backends-infra--terminal-reflow-filter))
        (setq ai-code-backends-infra--reflow-advised-handlers
              (delq handler ai-code-backends-infra--reflow-advised-handlers))))
    (unless enabled
      (when (advice-member-p #'ai-code-backends-infra--terminal-reflow-filter
                             resize-handler)
        (advice-remove resize-handler
                       #'ai-code-backends-infra--terminal-reflow-filter))
      (setq ai-code-backends-infra--reflow-advised-handlers
            (delq resize-handler ai-code-backends-infra--reflow-advised-handlers)))
    (when (and enabled resize-handler)
      (unless (advice-member-p #'ai-code-backends-infra--terminal-reflow-filter
                               resize-handler)
        (advice-add resize-handler
                    :around
                    #'ai-code-backends-infra--terminal-reflow-filter))
      (cl-pushnew resize-handler ai-code-backends-infra--reflow-advised-handlers
                  :test #'eq))))

(defun ai-code-backends-infra--display-buffer-in-side-window (buffer)
  "Display BUFFER in a side window."
  (let ((window
         (if ai-code-backends-infra-use-side-window
             (let* ((side ai-code-backends-infra-window-side)
                    (display-buffer-alist
                     `((,(regexp-quote (buffer-name buffer))
                        (display-buffer-in-side-window)
                        (side . ,side)
                        (slot . 0)
                        ,@(when (memq side '(left right))
                            `((window-width . ,#'ai-code-backends-infra--fit-side-window-body-width)
                              (preserve-size . (t . nil))))
                        ,@(when (memq side '(top bottom))
                            `((window-height . ,ai-code-backends-infra-window-height)
                              (preserve-size . (nil . t))))
                        (window-parameters . ((no-delete-other-windows . t)
                                              (window-size-fixed . ,(if (memq side '(left right)) 'width 'height))))))))
               (display-buffer buffer))
           (display-buffer buffer))))
    (setq ai-code-backends-infra--last-accessed-buffer buffer)
    (when (and window ai-code-backends-infra-focus-on-open)
      (select-window window))
    ;; Sync terminal dimensions with the actual window size.
    ;; The buffer may have been created with different dimensions before
    ;; being displayed in this window.
    (when (and window (buffer-live-p buffer))
      (ai-code-backends-infra--sync-terminal-dimensions buffer window)
      (with-current-buffer buffer
        (when (eq ai-code-backends-infra--session-terminal-backend 'ghostel)
          (ai-code-ghostel-image-preview-schedule-visible-linkify window))))
    window))

(defun ai-code-backends-infra--fit-side-window-body-width (window)
  "Resize WINDOW so its body width matches `ai-code-backends-infra-window-width'."
  (let ((delta (- ai-code-backends-infra-window-width
                  (window-body-width window))))
    (unless (zerop delta)
      (window-resize window delta t t))))

(defun ai-code-backends-infra--sync-terminal-dimensions (buffer window)
  "Sync terminal dimensions in BUFFER to match WINDOW size.
This ensures the terminal process has the correct dimensions after
the buffer has been displayed in its final window, which may differ
from the window where it was initially created."
  (when (and buffer window (buffer-live-p buffer) (window-live-p window))
    (with-current-buffer buffer
      (when-let* ((proc (get-buffer-process buffer)))
        (let ((backend (ai-code-backends-infra--current-terminal-backend))
              (windows (or (get-buffer-window-list buffer nil t)
                           (list window))))
          (if (eq backend 'ghostel)
              (set-process-window-size proc
                                       (window-body-height window)
                                       (window-body-width window))
            (pcase backend
              ('vterm
               (let ((result
                      (funcall (ai-code-backends-infra--terminal-resize-handler
                                'vterm)
                               proc windows)))
                 (when result
                   (ai-code-backends-infra-vterm-flush-render-queue buffer))
                 result))
              (_
               (set-process-window-size proc
                                        (window-body-height window)
                                        (window-body-width window))))))))))

;;; Session Helpers

(defun ai-code-backends-infra--session-working-directory (&optional prompt-p)
  "Return the working directory, preferring the current project root.
When PROMPT-P is non-nil, prompt with the computed directory as the default."
  (let ((working-dir (ai-code--session-project-root)))
    (if prompt-p
        (read-directory-name "Working directory: "
                             working-dir
                             working-dir
                             t)
      working-dir)))

(defun ai-code-backends-infra--normalize-session-directory (directory)
  "Return DIRECTORY normalized for robust session matching."
  (file-name-as-directory (file-truename (expand-file-name directory))))

(defun ai-code-backends-infra--normalize-file-path (file)
  "Return normalized absolute path for FILE."
  (expand-file-name file))

(declare-function magit-get-current-branch "magit-git" ())

(defun ai-code-backends-infra--sanitize-instance-name (instance-name)
  "Return INSTANCE-NAME with buffer name delimiters sanitized."
  (replace-regexp-in-string "]" "-" instance-name t t))

(defun ai-code-backends-infra--branch-instance-name (&optional existing-instance-names)
  "Return the current branch as an instance name, unless already used.
EXISTING-INSTANCE-NAMES is a list of existing instance names."
  (let* ((branch (ignore-errors (magit-get-current-branch)))
         (instance (and (stringp branch)
                        (ai-code-backends-infra--sanitize-instance-name
                         branch))))
    (when (and instance
               (not (string-empty-p instance))
               (not (member instance existing-instance-names)))
      instance)))

(defun ai-code-backends-infra--default-instance-name (&optional existing-instance-names)
  "Return the default instance name for the current buffer, or nil.
When the current git branch is available and not in EXISTING-INSTANCE-NAMES,
use the branch name."
  (ai-code-backends-infra--branch-instance-name existing-instance-names))

(defun ai-code-backends-infra--file-session-map-key (prefix source-buffer)
  "Return workspace-scoped file-session key for PREFIX and SOURCE-BUFFER."
  (when (and prefix (buffer-live-p source-buffer))
    (with-current-buffer source-buffer
      (when (and (stringp buffer-file-name)
                 (> (length buffer-file-name) 0))
        (list prefix
              (ai-code-backends-infra--normalize-session-directory
               (ai-code--session-project-root))
              (ai-code-backends-infra--normalize-file-path
               buffer-file-name))))))

(defun ai-code-backends-infra--remember-file-session-buffer (prefix source-buffer session-buffer)
  "Remember SESSION-BUFFER as attached session for SOURCE-BUFFER and PREFIX."
  (when-let* ((key (ai-code-backends-infra--file-session-map-key prefix source-buffer)))
    (if (and session-buffer (buffer-live-p session-buffer))
        (puthash key session-buffer ai-code-backends-infra--file-session-map)
      (remhash key ai-code-backends-infra--file-session-map))))

(defun ai-code-backends-infra--live-terminal-session-p (buffer)
  "Return non-nil when BUFFER is a managed terminal with a live process."
  (and (buffer-live-p buffer)
       (buffer-local-value
        'ai-code-backends-infra--session-terminal-backend buffer)
       (when-let* ((process (get-buffer-process buffer)))
         (process-live-p process))))

(defun ai-code-backends-infra--preferred-session (sessions)
  "Return an unambiguous session from SESSIONS, or nil."
  (cond
   ((memq ai-code-backends-infra--last-accessed-buffer sessions)
    ai-code-backends-infra--last-accessed-buffer)
   ((length= sessions 1) (car sessions))))

(defun ai-code-backends-infra--attached-sessions (source)
  "Return live sessions explicitly attached to SOURCE's file."
  (when-let* ((file (buffer-local-value 'buffer-file-name source))
              (normalized-file
               (ai-code-backends-infra--normalize-file-path file))
              (root (with-current-buffer source
                      (ai-code--session-project-root)))
              (normalized-root
               (ai-code-backends-infra--normalize-session-directory root)))
    (let (sessions)
      (maphash
       (lambda (key session)
         (when (and (equal (nth 1 key) normalized-root)
                    (equal (nth 2 key) normalized-file)
                    (ai-code-backends-infra--live-terminal-session-p session))
           (push session sessions)))
       ai-code-backends-infra--file-session-map)
      (delete-dups sessions))))

(defun ai-code-backends-infra--project-sessions (source)
  "Return live sessions belonging to SOURCE's current project."
  (when-let* ((root
               (with-current-buffer source
                 (ai-code--session-project-root)))
              (normalized-root
               (ignore-errors
                 (ai-code-backends-infra--normalize-session-directory root))))
    (seq-filter
     (lambda (session)
       (when-let* ((directory
                    (ai-code-backends-infra-session-directory session)))
         (string= directory normalized-root)))
     (ai-code-backends-infra-session-buffers))))

(defun ai-code-backends-infra-current-buffer-session (&optional buffer)
  "Return the unambiguous live TUI session associated with BUFFER.
BUFFER defaults to the current buffer.  Return BUFFER itself when it is a
managed terminal session.  Prefer a session explicitly attached to BUFFER's
file.  Otherwise use the sole session in BUFFER's project, or the most recently
accessed project session.  Return nil instead of choosing arbitrarily."
  (let ((source (or buffer (current-buffer))))
    (when (buffer-live-p source)
      (if (ai-code-backends-infra--live-terminal-session-p source)
          source
        (let ((attached (ai-code-backends-infra--attached-sessions source)))
          (or (ai-code-backends-infra--preferred-session attached)
              (unless attached
                (ai-code-backends-infra--preferred-session
                 (ai-code-backends-infra--project-sessions source)))))))))

(defun ai-code-backends-infra-session-buffers ()
  "Return all live managed terminal session buffers."
  (cl-remove-if-not #'ai-code-backends-infra--live-terminal-session-p
                    (buffer-list)))

(defun ai-code-backends-infra--send-string-with-paste
    (string paste send-function paste-function paste-active-p backend-name)
  "Send STRING safely through a terminal backend.
Use SEND-FUNCTION for ordinary input.  When PASTE is non-nil, use
PASTE-FUNCTION only while PASTE-ACTIVE-P returns non-nil, or report that
BACKEND-NAME cannot paste safely."
  (cond
   ((not paste) (funcall send-function string))
   ((and paste-function paste-active-p (funcall paste-active-p))
    (funcall paste-function string))
   (t
    (user-error
     "This %s session cannot paste multiline input without submitting"
     backend-name))))

(defun ai-code-backends-infra-insert-string (string buffer)
  "Insert STRING into TUI session BUFFER without submitting it.
Multiline input uses the terminal backend's paste operation so embedded
newlines are not interpreted as Return keys."
  (unless (ai-code-backends-infra--live-terminal-session-p buffer)
    (user-error "AI session is no longer available"))
  (with-current-buffer buffer
    (ai-code-backends-infra--terminal-send-string
     string (and (string-match-p "\n" string) t)))
  (setq ai-code-backends-infra--last-accessed-buffer buffer)
  (if-let* ((window (get-buffer-window buffer)))
      (select-window window)
    (ai-code-backends-infra--display-buffer-in-side-window buffer)))

(defun ai-code-backends-infra--attached-file-session (prefix source-buffer working-dir)
  "Return attached session state for PREFIX and SOURCE-BUFFER.
WORKING-DIR is the directory used to validate compatible sessions.
Return a cons of (BUFFER . MISSING-P)."
  (let ((key (ai-code-backends-infra--file-session-map-key prefix source-buffer)))
    (if (null key)
        (cons nil nil)
      (let* ((attached (gethash key ai-code-backends-infra--file-session-map))
             (valid (and (buffer-live-p attached)
                         (ai-code-backends-infra--session-buffer-matches-directory-p
                          attached
                          working-dir))))
        (cond
         (valid
          (cons attached nil))
         (attached
          (remhash key ai-code-backends-infra--file-session-map)
          (cons nil t))
         (t
          (cons nil nil)))))))

(defun ai-code-backends-infra--resolve-session-buffer (buffer-name missing-message prefix working-dir
                                                                  force-prompt source-buffer
                                                                  &optional any-session-fallback)
  "Resolve session buffer using BUFFER-NAME or selection rules.
MISSING-MESSAGE is used when no target session exists.
When PREFIX and WORKING-DIR are present, prefer the attached session for
SOURCE-BUFFER unless FORCE-PROMPT is non-nil.
When ANY-SESSION-FALLBACK is non-nil, prompt for any existing PREFIX
session if no session exists for WORKING-DIR."
  (let* ((file-session-key (and prefix
                                source-buffer
                                (ai-code-backends-infra--file-session-map-key
                                 prefix
                                 source-buffer)))
         (attached-state (and prefix working-dir
                              (ai-code-backends-infra--attached-file-session
                               prefix
                               source-buffer
                               working-dir)))
         (attached-buffer (car-safe attached-state))
         (attached-missing (cdr-safe attached-state))
         (needs-initial-file-selection (and (null buffer-name)
                                            file-session-key
                                            (null attached-buffer)
                                            (not attached-missing)))
         (effective-force-prompt
          (or force-prompt
              attached-missing
              needs-initial-file-selection))
         (buffer (or (and buffer-name (get-buffer buffer-name))
                     (and attached-buffer (not force-prompt) attached-buffer)
                     (and prefix working-dir
                          (let ((ai-code-backends-infra--preferred-session-buffer
                                 attached-buffer))
                            (ai-code-backends-infra--select-session-buffer
                             prefix
                             working-dir
                             effective-force-prompt))))))
    (when (and attached-missing (null buffer-name))
      (message "Attached AI session for this file no longer exists. Please select a target session again."))
    (if buffer
        (progn
          (ai-code-backends-infra--remember-session-buffer prefix working-dir buffer)
          (ai-code-backends-infra--remember-file-session-buffer prefix source-buffer buffer)
          buffer)
      (if-let ((fallback-buffer
                (and (null buffer-name)
                     prefix
                     any-session-fallback
                     (ai-code-backends-infra--select-any-session-buffer prefix))))
          (progn
            (when-let ((fallback-directory
                        (ai-code-backends-infra--buffer-session-directory
                         fallback-buffer)))
              (ai-code-backends-infra--remember-session-buffer
               prefix
               fallback-directory
               fallback-buffer))
            (ai-code-backends-infra--remember-file-session-buffer
             prefix
             source-buffer
             fallback-buffer)
            fallback-buffer)
        (user-error "%s" missing-message)))))

(defun ai-code-backends-infra--set-session-directory (buffer directory)
  "Store DIRECTORY on BUFFER for exact session matching."
  (when (and (buffer-live-p buffer) (stringp directory))
    (with-current-buffer buffer
      (setq-local ai-code-backends-infra--session-directory
                  (ai-code-backends-infra--normalize-session-directory directory)))))

(defun ai-code-backends-infra-session-directory (buffer)
  "Return BUFFER session directory, using legacy `default-directory' as fallback."
  (when (buffer-live-p buffer)
    (with-current-buffer buffer
      (cond
       ((and (stringp ai-code-backends-infra--session-directory)
             (> (length ai-code-backends-infra--session-directory) 0))
        (ai-code-backends-infra--normalize-session-directory
         ai-code-backends-infra--session-directory))
        ((and (stringp default-directory)
              (> (length default-directory) 0))
         (ai-code-backends-infra--normalize-session-directory
          default-directory))
        (t nil)))))

(defun ai-code-backends-infra--buffer-session-directory (buffer)
  "Return BUFFER session directory.
This is the internal accessor used by session selection code."
  (ai-code-backends-infra-session-directory buffer))

(defun ai-code-backends-infra--source-task-file (source-buffer)
  "Return the AI task file associated with SOURCE-BUFFER, or nil."
  (when (buffer-live-p source-buffer)
    (with-current-buffer source-buffer
      (when (and (stringp buffer-file-name)
                 (string-suffix-p ".org" buffer-file-name)
                 (or (derived-mode-p 'ai-code-prompt-mode)
                     (string-match-p "/\\.ai\\.code\\.files/" buffer-file-name)))
        (expand-file-name buffer-file-name)))))

(defun ai-code-backends-infra--sync-session-registry (buffer working-dir prefix
                                                             &optional task-file)
  "Register or update BUFFER in the AI session registry.
WORKING-DIR is the session root.  PREFIX identifies the backend.
TASK-FILE records the originating AI task file when available."
  (when (buffer-live-p buffer)
    (let ((resolved-task-file
           (or task-file
               (with-current-buffer buffer
                 ai-code-backends-infra--session-task-file))))
      (with-current-buffer buffer
        (setq-local ai-code-backends-infra--session-prefix prefix)
        (setq-local ai-code-backends-infra--session-task-file resolved-task-file))
      (ai-code-session-register
       :buffer buffer
       :backend prefix
       :repo-root working-dir
       :task-file resolved-task-file))))

(defun ai-code-backends-infra--session-buffer-name (prefix directory &optional instance-name)
  "Return a session buffer name for PREFIX in DIRECTORY.
When INSTANCE-NAME is non-nil and not \"default\", include it in the name."
  (let* ((base (file-name-nondirectory (directory-file-name directory)))
         (instance (and instance-name
                        (not (string= instance-name ""))
                        (not (string= instance-name "default"))
                        instance-name)))
    (format "*%s[%s%s]*"
            prefix
            base
            (if instance (format ":%s" instance) ""))))

(defun ai-code-backends-infra--normalize-instance-name (instance-name)
  "Return a normalized INSTANCE-NAME, defaulting to \"default\"."
  (if (and instance-name (not (string= instance-name "")))
      instance-name
    "default"))

(defun ai-code-backends-infra--session-key (directory instance-name)
  "Return a session key for DIRECTORY and INSTANCE-NAME."
  (cons (ai-code-backends-infra--normalize-session-directory directory)
        (ai-code-backends-infra--normalize-instance-name instance-name)))

(defun ai-code-backends-infra--session-map-key (prefix directory)
  "Return a map key for PREFIX and DIRECTORY."
  (cons prefix (ai-code-backends-infra--normalize-session-directory directory)))

(defun ai-code-backends-infra--parse-session-buffer-name (buffer-name prefix)
  "Parse BUFFER-NAME for PREFIX.
Return a cons of (base-name . instance-name) or nil."
  (when (string-match
         (format "\\`\\*%s\\[\\([^]:]+\\)\\(?::\\([^]]+\\)\\)?\\]\\*\\'"
                 (regexp-quote prefix))
         buffer-name)
    (cons (match-string 1 buffer-name)
          (match-string 2 buffer-name))))

(defun ai-code-backends-infra--session-instance-name (buffer-name prefix)
  "Return instance name for BUFFER-NAME with PREFIX."
  (when-let* ((parsed (ai-code-backends-infra--parse-session-buffer-name buffer-name prefix)))
    (ai-code-backends-infra--normalize-instance-name (cdr parsed))))

(defun ai-code-backends-infra--buffer-session-prefix-p (buffer prefix)
  "Return non-nil when BUFFER belongs to session PREFIX."
  (and (buffer-live-p buffer)
       (or (ai-code-backends-infra--parse-session-buffer-name
            (buffer-name buffer)
            prefix)
           (with-current-buffer buffer
             (equal ai-code-backends-infra--session-prefix prefix)))))

(defun ai-code-backends-infra--buffer-session-instance-name (buffer prefix)
  "Return BUFFER instance name for PREFIX."
  (or (ai-code-backends-infra--session-instance-name (buffer-name buffer) prefix)
      "default"))

(defun ai-code-backends-infra--all-session-buffers (prefix)
  "Return all live session buffers for PREFIX with known directories."
  (cl-remove-if-not
   (lambda (buffer)
     (and (ai-code-backends-infra--buffer-session-prefix-p buffer prefix)
          (ai-code-backends-infra--buffer-session-directory buffer)))
   (buffer-list)))

(defun ai-code-backends-infra--session-choice-label (prefix buffer)
  "Return a directory-oriented completion label for BUFFER and PREFIX."
  (let* ((directory (ai-code-backends-infra--buffer-session-directory buffer))
         (instance (ai-code-backends-infra--buffer-session-instance-name
                    buffer
                    prefix))
         (directory-label (abbreviate-file-name directory)))
    (if (string= instance "default")
        directory-label
      (format "%s [%s]" directory-label instance))))

(defun ai-code-backends-infra--uniquify-session-choices (choices)
  "Return CHOICES with duplicate labels disambiguated by buffer name."
  (let ((counts (make-hash-table :test 'equal)))
    (dolist (choice choices)
      (puthash (car choice)
               (1+ (gethash (car choice) counts 0))
               counts))
    (mapcar (lambda (choice)
              (let ((label (car choice))
                    (buffer (cdr choice)))
                (if (> (gethash label counts 0) 1)
                    (cons (format "%s - %s" label (buffer-name buffer))
                          buffer)
                  choice)))
            choices)))

(defun ai-code-backends-infra--select-any-session-buffer (prefix)
  "Prompt for an existing session buffer for PREFIX, listed by directory."
  (let* ((choices (sort
                   (mapcar (lambda (buffer)
                             (cons (ai-code-backends-infra--session-choice-label
                                    prefix
                                    buffer)
                                   buffer))
                           (ai-code-backends-infra--all-session-buffers prefix))
                   (lambda (left right)
                     (string< (car left) (car right)))))
         (unique-choices
          (ai-code-backends-infra--uniquify-session-choices choices)))
    (when unique-choices
      (let* ((candidates (mapcar #'car unique-choices))
             (selection (completing-read
                         (format "Select %s session by directory: " prefix)
                         candidates
                         nil t nil nil (car candidates))))
        (cdr (assoc selection unique-choices))))))

(defun ai-code-backends-infra--find-session-buffers (prefix directory)
  "Return session buffers for PREFIX in DIRECTORY."
  (let ((base (file-name-nondirectory (directory-file-name directory)))
        (target-directory (ai-code-backends-infra--normalize-session-directory directory)))
    (cl-remove-if-not
     (lambda (buf)
       (when-let* ((parsed (ai-code-backends-infra--parse-session-buffer-name
                            (buffer-name buf)
                            prefix)))
         (if-let* ((buffer-directory (ai-code-backends-infra-session-directory buf)))
             (string= (ai-code-backends-infra--normalize-session-directory buffer-directory)
                      target-directory)
           (string= (car parsed) base))))
     (buffer-list))))

(defun ai-code-backends-infra--remember-session-buffer (prefix directory buffer)
  "Remember BUFFER as the last selected session for PREFIX and DIRECTORY."
  (when (and prefix directory buffer)
    (puthash (ai-code-backends-infra--session-map-key prefix directory)
             buffer
             ai-code-backends-infra--directory-buffer-map)))

(defun ai-code-backends-infra--forget-session-buffer (prefix directory buffer)
  "Forget BUFFER if it's the remembered session for PREFIX and DIRECTORY."
  (when (and prefix directory buffer)
    (let* ((key (ai-code-backends-infra--session-map-key prefix directory))
           (existing (gethash key ai-code-backends-infra--directory-buffer-map)))
      (when (eq existing buffer)
        (remhash key ai-code-backends-infra--directory-buffer-map)))))

(defun ai-code-backends-infra--session-buffer-matches-directory-p (buffer directory)
  "Return non-nil when BUFFER is live and still belongs to DIRECTORY."
  (and (buffer-live-p buffer)
       (when-let* ((buffer-directory
                    (ai-code-backends-infra-session-directory buffer)))
         (string=
          (ai-code-backends-infra--normalize-session-directory buffer-directory)
          (ai-code-backends-infra--normalize-session-directory directory)))))

(defun ai-code-backends-infra--select-session-buffer (prefix directory &optional force-prompt)
  "Select a session buffer for PREFIX in DIRECTORY.
FORCE-PROMPT means always prompt even if a session was remembered.
Returns the selected buffer or nil if none exist."
  (let* ((remembered (gethash (ai-code-backends-infra--session-map-key prefix directory)
                              ai-code-backends-infra--directory-buffer-map))
         (buffers (ai-code-backends-infra--find-session-buffers prefix directory)))
    (when (and remembered
               (ai-code-backends-infra--session-buffer-matches-directory-p
                remembered
                directory)
               (not (memq remembered buffers)))
      (push remembered buffers))
    (cond
     ((null buffers) nil)
     ((= (length buffers) 1)
      (ai-code-backends-infra--remember-session-buffer prefix directory (car buffers))
      (car buffers))
     (t
      (let* ((preferred (if (memq ai-code-backends-infra--preferred-session-buffer buffers)
                            ai-code-backends-infra--preferred-session-buffer
                          (and (memq remembered buffers) remembered)))
             (ordered-buffers (if preferred
                                  (cons preferred (delq preferred (copy-sequence buffers)))
                                buffers))
             (choices (delq nil
                            (mapcar (lambda (buf)
                                      (when-let* ((instance
                                                   (ai-code-backends-infra--session-instance-name
                                                    (buffer-name buf)
                                                    prefix)))
                                        (cons instance buf)))
                                    ordered-buffers)))
             (candidates (mapcar #'car choices))
             (default-candidate (car candidates)))
        (if (and (not force-prompt) remembered (memq remembered buffers))
            remembered
          (let ((selection (completing-read
                            (format "Select %s session: " prefix)
                            candidates
                            nil t nil nil default-candidate)))
            (let ((buffer (cdr (assoc selection choices))))
              (ai-code-backends-infra--remember-session-buffer prefix directory buffer)
              buffer))))))))

(defun ai-code-backends-infra--prompt-for-instance-name (existing-instance-names
                                                         &optional force-prompt
                                                         default-instance-name)
  "Prompt for a new instance name.
EXISTING-INSTANCE-NAMES is a list of existing instance names.
If FORCE-PROMPT is nil and there are no existing instances, return the current
branch name when available; otherwise return \"default\".
DEFAULT-INSTANCE-NAME seeds the minibuffer when prompting."
  (if (or existing-instance-names force-prompt)
      (let ((proposed-name ""))
        (while (or (string= proposed-name "")
                   (member proposed-name existing-instance-names))
          (setq proposed-name
                (let ((default-input (or (and (> (length proposed-name) 0)
                                              proposed-name)
                                         default-instance-name)))
                  (read-string (if existing-instance-names
                                   (format "Instance name (existing: %s): "
                                           (mapconcat #'identity existing-instance-names ", "))
                                  "Instance name: ")
                               default-input nil default-input)))
          (cond
           ((string= proposed-name "")
            (message "Instance name cannot be empty. Please enter a name.")
            (sit-for 1))
           ((member proposed-name existing-instance-names)
            (message "Instance name '%s' already exists. Please choose a different name." proposed-name)
            (sit-for 1))))
        proposed-name)
    (or (ai-code-backends-infra--branch-instance-name existing-instance-names)
        "default")))

(defun ai-code-backends-infra--resume-switch-p (switches)
  "Check resume-style CLI flag presence.
SWITCHES is the command argument list."
  (cl-some (lambda (switch)
             (member switch '("resume" "--resume" "--continue")))
           switches))

(defun ai-code-backends-infra--read-session-working-directory (default-dir)
  "Read a session working directory using DEFAULT-DIR as the default."
  (file-name-as-directory
   (expand-file-name
    (read-directory-name "Start AI CLI in directory: "
                         default-dir default-dir t))))

(defun ai-code-backends-infra--resolve-start-command (program switches arg &optional prompt-label)
  "Resolve PROGRAM and its arguments into display and argv forms.
SWITCHES is the default command-line argument list.
Use it as default input when ARG is non-nil and CLI args are prompted.
PROMPT-LABEL is used in the minibuffer prompt.
When resuming and the active region contains a UUID, prompt as though ARG
were non-nil and append that UUID to the default CLI args."
  (let* ((found-resume-switch
          (ai-code-backends-infra--resume-switch-p switches))
         (selected-session-id
          (and (null arg)
               found-resume-switch
               (ai-code-backends-infra--selected-session-id)))
         (prompt-p (or arg selected-session-id))
         (default-args (mapconcat #'identity
                                   (append switches
                                           (and selected-session-id
                                                (list selected-session-id)))
                                   " "))
         (prompt (format "%s args: " (or prompt-label "CLI")))
         (prompt-args (when prompt-p
                           (read-string prompt default-args 'ai-code-cli-args-history)))
         (resolved-args (if prompt-p
                            (split-string-shell-command prompt-args)
                          switches))
         (command (mapconcat #'identity
                             (cons program resolved-args)
                             " ")))
    (list :command command
          :argv (cons program resolved-args)
          :args resolved-args)))

(defun ai-code-backends-infra--command-argv (command)
  "Return COMMAND as an argv list.
COMMAND may be an argv list or a legacy shell command string."
  (cond
   ((null command) nil)
   ((and (listp command) (seq-every-p #'stringp command)) command)
   ((stringp command) (split-string-shell-command command))
   (t (error "Invalid CLI command: %S" command))))

(defun ai-code-backends-infra--cleanup-session (directory buffer-name process-table
                                                          &optional instance-name prefix event)
  "Clean up a session for DIRECTORY using BUFFER-NAME and PROCESS-TABLE.
INSTANCE-NAME and PREFIX identify the session map entry to remove.
EVENT is the process sentinel event string.  When EVENT is non-nil and does
not start with \"finished\", the buffer is preserved so the user can inspect
any error output left behind by the CLI."
  (let* ((resolved-instance (or instance-name
                                (and prefix
                                     (ai-code-backends-infra--session-instance-name
                                      buffer-name
                                      prefix))
                                 "default"))
         (key (ai-code-backends-infra--session-key directory resolved-instance)))
    (remhash key process-table))
  (when-let* ((buffer (get-buffer buffer-name)))
    (ai-code-backends-infra--forget-session-buffer prefix directory buffer)
    (ai-code-session-unregister buffer)
    (when (buffer-live-p buffer)
      (when (or (null event)
                (string-prefix-p "finished" event))
        (kill-buffer buffer)))))

(defun ai-code-backends-infra--resolve-session-target (working-dir buffer-name
                                                                   prefix instance-name
                                                                   force-prompt)
  "Return resolved session target information.
WORKING-DIR is the session directory.
BUFFER-NAME is the explicit terminal buffer name, when provided.
PREFIX enables instance-based naming.
INSTANCE-NAME overrides interactive instance selection when non-nil.
FORCE-PROMPT forces instance prompting when PREFIX is non-nil.
Return a plist with :instance-name, :buffer-name, and :session-key."
  (let* ((existing-buffers (and prefix
                                (ai-code-backends-infra--find-session-buffers
                                 prefix
                                 working-dir)))
         (existing-instance-names (mapcar (lambda (buf)
                                            (ai-code-backends-infra--session-instance-name
                                             (buffer-name buf)
                                             prefix))
                                          existing-buffers))
         (resolved-instance (cond
                             (instance-name
                              (ai-code-backends-infra--normalize-instance-name instance-name))
                             (prefix
                              (ai-code-backends-infra--prompt-for-instance-name
                               existing-instance-names
                               force-prompt
                               (ai-code-backends-infra--default-instance-name
                                existing-instance-names)))
                             (t "default")))
         (resolved-buffer-name (or buffer-name
                                    (and prefix
                                         (ai-code-backends-infra--session-buffer-name
                                          prefix
                                         working-dir
                                         resolved-instance)))))
    (list :instance-name resolved-instance
          :buffer-name resolved-buffer-name
          :session-key (ai-code-backends-infra--session-key
                        working-dir
                        resolved-instance))))

(defun ai-code-backends-infra--resolve-session-context (working-dir buffer-name
                                                                    process-table
                                                                    prefix instance-name
                                                                    force-prompt)
  "Return resolved session context for session lifecycle operations.
WORKING-DIR is the session directory.
BUFFER-NAME is the explicit terminal buffer name, when provided.
PROCESS-TABLE maps session keys to processes.
PREFIX enables instance-based naming.
INSTANCE-NAME overrides interactive instance selection when non-nil.
FORCE-PROMPT forces instance prompting when PREFIX is non-nil.
Return a plist with target information plus the current buffer and process."
  (let* ((session-target (ai-code-backends-infra--resolve-session-target
                          working-dir
                          buffer-name
                          prefix
                          instance-name
                          force-prompt))
         (session-key (plist-get session-target :session-key))
         (resolved-buffer-name (plist-get session-target :buffer-name)))
    (append session-target
            (list :buffer (get-buffer resolved-buffer-name)
                  :existing-process (gethash session-key process-table)))))

(defun ai-code-backends-infra--reuse-session-window (buffer working-dir
                                                            prefix multiline-input-sequence
                                                            &optional task-file)
  "Toggle visibility for an existing session BUFFER.
WORKING-DIR, PREFIX, MULTILINE-INPUT-SEQUENCE, and TASK-FILE refresh session
state.
When BUFFER is already visible, close its window.
Otherwise refresh session-local state and display it."
  (if (get-buffer-window buffer)
      (delete-window (get-buffer-window buffer))
    (ai-code-backends-infra--set-session-directory buffer working-dir)
    (ai-code-backends-infra--configure-session-buffer
     buffer nil multiline-input-sequence)
    (ai-code-backends-infra--remember-session-buffer prefix working-dir buffer)
    (ai-code-backends-infra--sync-session-registry
     buffer working-dir prefix task-file)
    (ai-code-backends-infra--display-buffer-in-side-window buffer)))

(defun ai-code-backends-infra--finalize-started-session (buffer process
                                                                 working-dir buffer-name
                                                                 process-table resolved-instance
                                                                 prefix escape-fn cleanup-fn
                                                                 multiline-input-sequence
                                                                 post-start-fn
                                                                 &optional task-file)
  "Finalize a successfully started session BUFFER and PROCESS.
WORKING-DIR, BUFFER-NAME, PROCESS-TABLE, RESOLVED-INSTANCE, and PREFIX
identify the session for cleanup and reuse.  ESCAPE-FN, CLEANUP-FN,
MULTILINE-INPUT-SEQUENCE, POST-START-FN, and TASK-FILE install session
behavior."
  (let ((previous-sentinel
         (ignore-errors
           (process-get process 'ai-code-backends-infra--ghostel-sentinel))))
    (set-process-sentinel
     process
     (lambda (proc event)
       (when previous-sentinel
         (ignore-errors
           (funcall previous-sentinel proc event)))
       (ai-code-backends-infra--cleanup-session
        working-dir
        buffer-name
        process-table
        resolved-instance
        prefix
        event)
       (when cleanup-fn
         (funcall cleanup-fn)))))
  (ai-code-backends-infra--configure-session-buffer
   buffer escape-fn multiline-input-sequence)
  (when post-start-fn
    (funcall post-start-fn buffer process resolved-instance))
  (with-current-buffer buffer
    (add-hook 'kill-buffer-hook
              (lambda ()
                (ai-code-session-unregister (current-buffer))
                (ai-code-backends-infra--forget-session-buffer
                 prefix
                 working-dir
                 (current-buffer)))
              nil t))
  (ai-code-backends-infra--remember-session-buffer prefix working-dir buffer)
  (ai-code-backends-infra--sync-session-registry
   buffer working-dir prefix task-file)
  (ai-code-backends-infra--display-buffer-in-side-window buffer))

(defun ai-code-backends-infra--handle-session-start-failure (buffer session-key process-table)
  "Handle startup failure for BUFFER and SESSION-KEY in PROCESS-TABLE."
  (remhash session-key process-table)
  (if (buffer-live-p buffer)
      (progn
        (pop-to-buffer buffer)
        (message "CLI failed to start - see buffer for error details"))
    (message "CLI failed to start - process exited immediately")))

(defun ai-code-backends-infra--cleanup-failed-launch (cleanup-fn)
  "Call CLEANUP-FN after a failed launch without masking the startup error."
  (when cleanup-fn
    (condition-case err
        (funcall cleanup-fn)
      (error
       (display-warning
        'ai-code-backends-infra
        (format "Failed to clean up CLI launch resources: %s"
                (error-message-string err)))))))

(defun ai-code-backends-infra--start-cli-session (options arg)
  "Start a generic CLI session described by OPTIONS and prefix ARG.
When ARG is non-nil for normal starts, prompt for the working directory.
OPTIONS is a plist with these keys:
:program is the CLI executable.
:switches is the default list of CLI switches.
:label is the user-facing CLI label.
:process-table maps session keys to processes.
:session-prefix is the session buffer prefix.
:escape-function is an optional function bound to escape in the
session buffer.
:env-vars is an optional list of environment variable strings.
:multiline-input-sequence is an optional terminal sequence for
multiline input.
:prepare-launch is an optional function called with (WORKING-DIR ARGV).
When :prepare-launch is present, it may return :argv, :env-vars,
:cleanup-fn, and :post-start-fn entries to customize session creation.
A legacy :command entry is normalized to argv for compatibility.

For normal starts, non-nil ARG prompts for the working directory.  For
resume-style invocations, ARG is still passed through so the user can edit
the resume command-line arguments."
  (let* ((switches (plist-get options :switches))
         (resume-start-p (ai-code-backends-infra--resume-switch-p switches))
         (default-working-dir (ai-code-backends-infra--session-working-directory))
         (working-dir (if (and arg (not resume-start-p))
                          (ai-code-backends-infra--read-session-working-directory
                           default-working-dir)
                        default-working-dir))
         (command-arg (and (or (not arg) resume-start-p) arg))
         (resolved (ai-code-backends-infra--resolve-start-command
                    (plist-get options :program)
                    switches
                    command-arg
                    (plist-get options :label)))
         (argv
          (ai-code-backends-infra--command-argv
           (or (plist-get resolved :argv)
               (plist-get resolved :command))))
         (launch (when-let* ((prepare-launch (plist-get options :prepare-launch)))
                   (funcall prepare-launch working-dir argv)))
         (launch-argv
          (ai-code-backends-infra--command-argv
           (or (plist-get launch :argv)
               (plist-get launch :command)
               argv)))
         (launch-env-vars (plist-get launch :env-vars))
         (cleanup-fn (plist-get launch :cleanup-fn))
         (post-start-fn (plist-get launch :post-start-fn)))
    (let ((ai-code-backends-infra--launch-program
           (plist-get options :program)))
      (ai-code-backends-infra--toggle-or-create-session
       working-dir
       nil
       (plist-get options :process-table)
       launch-argv
       (plist-get options :escape-function)
       cleanup-fn
       nil
       (plist-get options :session-prefix)
       (and resume-start-p arg)
       (append launch-env-vars (plist-get options :env-vars))
       (plist-get options :multiline-input-sequence)
       post-start-fn))))

(defun ai-code-backends-infra--last-accessed-session-buffer (session-prefix)
  "Return the last accessed buffer when it belongs to SESSION-PREFIX."
  (let ((buffer ai-code-backends-infra--last-accessed-buffer))
    (when (and (buffer-live-p buffer)
               (with-current-buffer buffer
                 (or (and (stringp ai-code-backends-infra--session-prefix)
                          (string= ai-code-backends-infra--session-prefix
                                   session-prefix))
                     (ai-code-backends-infra--parse-session-buffer-name
                      (buffer-name buffer)
                      session-prefix))))
      buffer)))

(defun ai-code-backends-infra--cli-switch-to-buffer (label session-prefix force-prompt)
  "Switch to a CLI backend session.
LABEL is used in the missing-session message.  SESSION-PREFIX identifies
the backend session group.  FORCE-PROMPT prompts for a session when non-nil."
  (let ((working-dir (ai-code-backends-infra--session-working-directory)))
    (ai-code-backends-infra--switch-to-session-buffer
     nil
     (format "No %s session for this project" label)
     session-prefix
     working-dir
     force-prompt)))

(defun ai-code-backends-infra--cli-send-command (label session-prefix line)
  "Send LINE to a CLI backend session.
LABEL is used in the missing-session message.  SESSION-PREFIX identifies
the backend session group."
  (let ((working-dir (ai-code-backends-infra--session-working-directory)))
    (ai-code-backends-infra--send-line-to-session
     nil
     (format "No %s session for this project" label)
     line
     session-prefix
     working-dir)))

(defun ai-code-backends-infra--cli-show-resume-picker (session-prefix)
  "Poke the resumed SESSION-PREFIX buffer so the CLI picker is shown."
  (let* ((working-dir (ai-code-backends-infra--session-working-directory))
         (buffer (or (ai-code-backends-infra--last-accessed-session-buffer
                      session-prefix)
                     (ai-code-backends-infra--select-session-buffer
                      session-prefix
                      working-dir))))
    (when buffer
      (with-current-buffer buffer
        (sit-for 0.5)
        (ai-code-backends-infra--terminal-send-string "")
        (goto-char (point-min))))))

(defun ai-code-backends-infra--prepare-session-request (working-dir buffer-name
                                                                    process-table
                                                                    prefix instance-name
                                                                    force-prompt)
  "Prepare runtime context for toggling or creating a session.
WORKING-DIR, BUFFER-NAME, PROCESS-TABLE, PREFIX, INSTANCE-NAME, and
FORCE-PROMPT match `ai-code-backends-infra--toggle-or-create-session'.
Return a plist containing source buffer, task file, and resolved session
context values."
  (ai-code-backends-infra--cleanup-dead-processes process-table)
  (let* ((source-buffer (current-buffer))
         (task-file (ai-code-backends-infra--source-task-file source-buffer))
         (session-context (ai-code-backends-infra--resolve-session-context
                           working-dir
                           buffer-name
                           process-table
                           prefix
                           instance-name
                           force-prompt)))
    (append session-context
            (list :source-buffer source-buffer
                  :task-file task-file))))

(defun ai-code-backends-infra--reuse-existing-session (buffer working-dir
                                                              prefix
                                                              multiline-input-sequence
                                                              task-file
                                                              source-buffer)
  "Reuse an existing live session BUFFER.
WORKING-DIR, PREFIX, MULTILINE-INPUT-SEQUENCE, TASK-FILE, and SOURCE-BUFFER
refresh session state and preserve file-to-session binding."
  (ai-code-backends-infra--reuse-session-window
   buffer
   working-dir
   prefix
   multiline-input-sequence
   task-file)
  (ai-code-backends-infra--remember-file-session-buffer
   prefix source-buffer buffer))

(defun ai-code-backends-infra--create-new-session (resolved-buffer-name
                                                   working-dir command env-vars
                                                   session-key process-table
                                                   resolved-instance prefix
                                                   escape-fn cleanup-fn
                                                   multiline-input-sequence
                                                   post-start-fn
                                                   task-file source-buffer)
  "Create and finalize a new session buffer.
RESOLVED-BUFFER-NAME, WORKING-DIR, COMMAND, and ENV-VARS create the terminal.
COMMAND is an argv list or a legacy shell command string.
SESSION-KEY and PROCESS-TABLE register the process.
RESOLVED-INSTANCE, PREFIX, ESCAPE-FN, CLEANUP-FN,
MULTILINE-INPUT-SEQUENCE, and POST-START-FN configure startup behavior.
TASK-FILE and SOURCE-BUFFER preserve file-to-session binding."
  (let* ((editor-environment
          (if (file-remote-p working-dir)
              env-vars
            (ai-code-editor-viewport-environment env-vars)))
         (buffer-and-process
          (condition-case err
              (ai-code-backends-infra--create-terminal-session
               resolved-buffer-name working-dir command editor-environment)
            (error
             (ai-code-backends-infra--cleanup-failed-launch cleanup-fn)
             (signal (car err) (cdr err)))))
         (new-buffer (car buffer-and-process))
         (process (cdr buffer-and-process)))
    (puthash session-key process process-table)
    ;; Wait for initialization before checking process status
    (sleep-for ai-code-backends-infra-terminal-initialization-delay)
    ;; Check if process is still alive after initialization delay
    (if (and process (process-live-p process))
        (progn
          (ai-code-backends-infra--finalize-started-session
           new-buffer
           process
           working-dir
           resolved-buffer-name
           process-table
           resolved-instance
           prefix
           escape-fn
           cleanup-fn
           multiline-input-sequence
           post-start-fn
           task-file)
          (ai-code-backends-infra--remember-file-session-buffer
           prefix source-buffer new-buffer))
      (unwind-protect
          (ai-code-backends-infra--handle-session-start-failure
           new-buffer
           session-key
           process-table)
        (ai-code-backends-infra--cleanup-failed-launch cleanup-fn)))))

(defun ai-code-backends-infra--toggle-or-create-session (working-dir buffer-name process-table command
                                                                     &optional escape-fn cleanup-fn
                                                                     instance-name prefix force-prompt
                                                                     env-vars multiline-input-sequence
                                                                     post-start-fn)
  "Toggle or create a terminal session.
WORKING-DIR is the directory for the session.
BUFFER-NAME is the terminal buffer name.
PROCESS-TABLE maps session keys to processes.
COMMAND is an argv list or a legacy shell command string.
ESCAPE-FN is bound to `C-<escape>' inside the session buffer when non-nil.
CLEANUP-FN is called with no arguments when the process exits or when an
existing session makes the prepared launch unnecessary.
INSTANCE-NAME overrides instance selection when non-nil.
PREFIX enables instance selection when BUFFER-NAME is nil.
When FORCE-PROMPT is non-nil, always prompt for a new instance name.
ENV-VARS is a list of additional environment variable strings, for example
\"VAR=value\", passed to the terminal session on creation.
MULTILINE-INPUT-SEQUENCE configures `S-<return>' and `C-<return>' to send
that sequence inside the session buffer.
POST-START-FN is called with (BUFFER PROCESS INSTANCE-NAME) after a new
session starts successfully."
  (setq process-table (or process-table ai-code-backends-infra--processes))
  (let* ((session-context
          (ai-code-backends-infra--prepare-session-request
           working-dir
           buffer-name
           process-table
           prefix
           instance-name
           force-prompt))
         (source-buffer (plist-get session-context :source-buffer))
         (task-file (plist-get session-context :task-file))
         (resolved-instance (plist-get session-context :instance-name))
         (resolved-buffer-name (plist-get session-context :buffer-name))
         (session-key (plist-get session-context :session-key))
         (existing-process (plist-get session-context :existing-process))
         (buffer (plist-get session-context :buffer)))
    (if (and existing-process (process-live-p existing-process) buffer)
        (unwind-protect
            (ai-code-backends-infra--reuse-existing-session
             buffer
             working-dir
             prefix
             multiline-input-sequence
             task-file
             source-buffer)
          (when cleanup-fn
            (funcall cleanup-fn)))
      (ai-code-backends-infra--create-new-session
       resolved-buffer-name
       working-dir
       command
       env-vars
       session-key
       process-table
       resolved-instance
       prefix
       escape-fn
       cleanup-fn
       multiline-input-sequence
       post-start-fn
       task-file
       source-buffer))))

(defun ai-code-backends-infra--switch-to-session-buffer (buffer-name missing-message
                                                                    &optional prefix working-dir force-prompt)
  "Switch to BUFFER-NAME or signal MISSING-MESSAGE.
FORCE-PROMPT means always prompt when PREFIX and WORKING-DIR are provided.
When PREFIX and WORKING-DIR are provided, select from multiple sessions."
  (let* ((source-buffer (current-buffer))
         (buffer (ai-code-backends-infra--resolve-session-buffer
                  buffer-name
                  missing-message
                  prefix
                  working-dir
                  force-prompt
                  source-buffer
                  t)))
    (if-let* ((window (get-buffer-window buffer)))
        (select-window window)
      (ai-code-backends-infra--display-buffer-in-side-window buffer))))

(defun ai-code-backends-infra--send-line-to-session (buffer-name missing-message line
                                                                &optional prefix working-dir force-prompt)
  "Send LINE to BUFFER-NAME or signal MISSING-MESSAGE.
When PREFIX and WORKING-DIR are provided, select from multiple sessions."
  (let* ((source-buffer (current-buffer))
         (buffer (ai-code-backends-infra--resolve-session-buffer
                  buffer-name
                  missing-message
                  prefix
                  working-dir
                  force-prompt
                  source-buffer
                  t)))
    (when (fboundp 'ai-code-mcp-agent-refresh-source-context)
      (ai-code-mcp-agent-refresh-source-context buffer source-buffer))
    (with-current-buffer buffer
      (ai-code-backends-infra--remember-session-buffer
       prefix
       (or (ai-code-backends-infra--buffer-session-directory buffer)
           working-dir)
       buffer)
      (if (and (string-match-p "\n" line)
               (member ai-code-backends-infra--session-prefix
                       ai-code-backends-infra-use-paste-backends))
          (ai-code-backends-infra--terminal-send-string line t)
        (ai-code-backends-infra--terminal-send-string line))
      (sit-for 0.5) ;; 0.1 might be too low for some cli backends such as github copilot cli
      (ai-code-backends-infra--terminal-send-return))))

;;; Generic Session Creation

(defun ai-code-backends-infra--create-terminal-session (buffer-name working-dir command env-vars)
  "Generic function to create a terminal session.
BUFFER-NAME is the name for the buffer.
WORKING-DIR is the directory.
COMMAND is an argv list or a legacy shell command string.
ENV-VARS is a list of environment variables."
  (let ((argv (ai-code-backends-infra--command-argv command)))
    (ai-code-backends-infra--terminal-ensure-backend)
    (pcase ai-code-backends-infra-terminal-backend
      ('vterm
       (ai-code-backends-infra-vterm-create-session
        buffer-name working-dir argv env-vars))
      ('eat
       (ai-code-backends-infra-eat-create-session
        buffer-name working-dir argv env-vars))
      ('ghostel
       (ai-code-backends-infra-ghostel-create-session
        buffer-name working-dir argv env-vars))
      (_ (error "Unknown backend")))))

(defun ai-code-backends-infra--cleanup-dead-processes (table)
  "Clean up dead processes from TABLE."
  (maphash (lambda (key proc)
             (unless (process-live-p proc)
               (remhash key table)))
           table))

;;; Evil Mode Integration

(defvar ai-code-backends-infra--evil-original-spc-command nil
  "Original command for SPC in `evil-normal-state-map'.")

(declare-function ai-code-send-command "ai-code" (&optional arg))

(defun ai-code-backends-infra--evil-spc-command ()
  "In AI session buffers, run `ai-code-send-command'.
Otherwise, run the original command for SPC."
  (interactive)
  (if (ai-code-backends-infra--session-buffer-p (current-buffer))
      (call-interactively #'ai-code-send-command)
    (when ai-code-backends-infra--evil-original-spc-command
      (call-interactively ai-code-backends-infra--evil-original-spc-command))))

;;;###autoload
(defun ai-code-backends-infra-evil-setup ()
  "Setup AI Code integration with Evil mode.
This function configures SPC key binding in Evil normal state for
AI session buffers.  Call this function after Evil is loaded,
typically in your Emacs configuration with:
  (with-eval-after-load \\='evil (ai-code-backends-infra-evil-setup))"
  (interactive)
  (when (and (featurep 'evil) (boundp 'evil-normal-state-map))
    (unless ai-code-backends-infra--evil-original-spc-command
      (setq ai-code-backends-infra--evil-original-spc-command
            (lookup-key evil-normal-state-map (kbd "SPC"))))
    (define-key evil-normal-state-map (kbd "SPC")
                #'ai-code-backends-infra--evil-spc-command)))

(require 'ai-code-backends-infra-etc)
(ai-code-backends-infra-etc-activate)

(provide 'ai-code-backends-infra)
;;; ai-code-backends-infra.el ends here
